export default [
    {
        id: '0',
        name: 'Emeka Emmanuel',
        date: '23/2/2018',
        type: 'Repair',
        status: 'Pending',
        description: 'I want to run some maintenance no my car.',
        sorting: 1537413578166,
    },
    {
        id: '1',
        name: 'Emeka Emmanuel',
        date: '23/2/2018',
        type: 'Repair',
        status: 'Pending',
        description: 'I want to run some maintenance no my car.',
        sorting: 1537412578166,
    },
    {
        id: '2',
        name: 'Emeka Emmanuel',
        date: '23/2/2018',
        type: 'Repair',
        status: 'Accepted',
        description: 'I want to run some maintenance no my car.',
        sorting: 1537317578166,
    },
    {
        id: '3',
        name: 'Emeka Emmanuel',
        date: '23/2/2018',
        type: 'Repair',
        status: 'Accepted',
        description: 'I want to run some maintenance no my car.',
        sorting: 1537217578166,
    },
    {
        id: '4',
        name: 'Patric Usman',
        date: '03/4/2018',
        type: 'Maintenance',
        status: 'Accepted',
        description: 'I want to run some maintenance no my car.',
        sorting: 1537117189043,
    },
    {
        id: '5',
        name: 'Patric Usman',
        date: '24/6/2018',
        type: 'Repair',
        status: 'Rejected',
        description: 'I want to run some maintenance no my car.',
        sorting: 1537117189040,
    },
    {
        id: '6',
        name: 'Emeka Emmanuel',
        date: '23/2/2018',
        type: 'Repair',
        status: 'Resolved',
        description: 'I want to run some repair no my car.',
        sorting: 1537117189023,
    },
    {
        id: '7',
        name: 'Patric Usman',
        date: '09/5/2018',
        type: 'Maintenance',
        status: 'Resolved',
        description: 'I want to run some maintenance no my car.',
        sorting: 1537117189013,
    },
];
